// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmcjxwaiqrprtgmdtbfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtY2p4d2FpcXJwcnRnbWR0YmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMTg4NTIsImV4cCI6MjA4NTc5NDg1Mn0.7buWPZeiI2wRHJuR0tP4nSaC8lbmFD2CAlvBjDY1as8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});